import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import {
  Search,
  Download,
  FileText,
  FileSpreadsheet,
  Eye,
  Trash2,
  Plus,
  FileBarChart,
  Files,
  Sparkles,
  X,
  ChevronLeft,
  ChevronRight,
} from "lucide-react";
import { toast } from "sonner";

import { DashboardShell } from "@/components/dashboard/DashboardShell";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { REPORTS, formatDate, type ReportRecord } from "@/lib/mock-data";

export const Route = createFileRoute("/reports/history")({
  head: () => ({
    meta: [
      { title: "Report History — Task Align" },
      { name: "description", content: "Browse and download previously generated assignment reports." },
    ],
  }),
  component: ReportHistoryPage,
});

const TYPES = ["Employee", "Developer", "Teacher", "Sales Region", "Flight Crew", "Manager Room"];

function ReportHistoryPage() {
  const [rows, setRows] = useState<ReportRecord[]>(REPORTS);
  const [query, setQuery] = useState("");
  const [type, setType] = useState("all");
  const [format, setFormat] = useState("all");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");
  const [pageSize, setPageSize] = useState(10);
  const [page, setPage] = useState(1);
  const [toDelete, setToDelete] = useState<ReportRecord | null>(null);

  const filtered = useMemo(() => {
    return rows.filter((r) => {
      const q = query.toLowerCase();
      const matchQ =
        !q ||
        r.name.toLowerCase().includes(q) ||
        r.assignmentName.toLowerCase().includes(q) ||
        r.id.toLowerCase().includes(q);
      const matchT = type === "all" || r.assignmentType === type;
      const matchF = format === "all" || r.format === format;
      const matchFrom = !dateFrom || r.generatedDate >= dateFrom;
      const matchTo = !dateTo || r.generatedDate <= dateTo;
      return matchQ && matchT && matchF && matchFrom && matchTo;
    });
  }, [rows, query, type, format, dateFrom, dateTo]);

  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize));
  const currentPage = Math.min(page, totalPages);
  const paged = filtered.slice((currentPage - 1) * pageSize, currentPage * pageSize);

  const pdfCount = rows.filter((r) => r.format === "PDF").length;
  const excelCount = rows.filter((r) => r.format === "Excel").length;
  const latest = [...rows].sort((a, b) => b.generatedDate.localeCompare(a.generatedDate))[0];

  const summary = [
    { label: "Total Reports", value: rows.length, icon: Files, tone: "from-violet-500/15 to-violet-500/5 text-violet-600" },
    { label: "PDF Reports", value: pdfCount, icon: FileText, tone: "from-rose-500/15 to-rose-500/5 text-rose-600" },
    { label: "Excel Reports", value: excelCount, icon: FileSpreadsheet, tone: "from-emerald-500/15 to-emerald-500/5 text-emerald-600" },
    { label: "Latest Report", value: latest ? formatDate(latest.generatedDate) : "—", icon: Sparkles, tone: "from-amber-500/15 to-amber-500/5 text-amber-600" },
  ];

  const clearFilters = () => {
    setQuery("");
    setType("all");
    setFormat("all");
    setDateFrom("");
    setDateTo("");
    setPage(1);
  };

  const exportHistory = () => {
    const header = ["ID", "Name", "Assignment", "Type", "Generated By", "Date", "Format"];
    const lines = [header.join(",")].concat(
      filtered.map((r) => [r.id, r.name, r.assignmentName, r.assignmentType, r.generatedBy, r.generatedDate, r.format].join(",")),
    );
    const blob = new Blob([lines.join("\n")], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "report-history.csv";
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Report history exported");
  };

  return (
    <DashboardShell>
      <header className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div className="space-y-1">
          <p className="text-xs font-semibold uppercase tracking-wider text-primary">Insights</p>
          <h1 className="text-2xl font-semibold tracking-tight md:text-3xl">Report History</h1>
          <p className="text-sm text-muted-foreground">Access every report you've generated across all assignments.</p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <Button variant="outline" className="rounded-xl" onClick={exportHistory}>
            <Download className="h-4 w-4" /> Export Report History
          </Button>
          <Button className="rounded-xl shadow-soft" onClick={() => toast.info("Choose an assignment to report on")}>
            <Plus className="h-4 w-4" /> Generate New Report
          </Button>
        </div>
      </header>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        {summary.map((s) => (
          <Card key={s.label} className={`rounded-2xl border-border/60 shadow-soft bg-gradient-to-br ${s.tone}`}>
            <CardContent className="flex items-center justify-between p-5">
              <div>
                <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">{s.label}</p>
                <p className="mt-2 text-2xl font-semibold tabular-nums">{s.value}</p>
              </div>
              <div className="rounded-xl bg-background/70 p-2.5 shadow-sm">
                <s.icon className="h-5 w-5" />
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      <Card className="sticky top-[64px] z-10 rounded-2xl border-border/60 shadow-soft">
        <CardContent className="space-y-4 p-4 md:p-5">
          <div className="relative">
            <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              value={query}
              onChange={(e) => {
                setQuery(e.target.value);
                setPage(1);
              }}
              placeholder="Search by Report Name, Assignment or ID..."
              className="h-10 rounded-xl pl-9"
            />
          </div>
          <div className="grid grid-cols-2 gap-2 md:grid-cols-4">
            <div className="space-y-1">
              <label className="text-[11px] font-medium text-muted-foreground">Assignment Type</label>
              <Select value={type} onValueChange={setType}>
                <SelectTrigger className="h-9 rounded-lg"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Types</SelectItem>
                  {TYPES.map((t) => <SelectItem key={t} value={t}>{t}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1">
              <label className="text-[11px] font-medium text-muted-foreground">Report Type</label>
              <Select value={format} onValueChange={setFormat}>
                <SelectTrigger className="h-9 rounded-lg"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Formats</SelectItem>
                  <SelectItem value="PDF">PDF</SelectItem>
                  <SelectItem value="Excel">Excel</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-1">
              <label className="text-[11px] font-medium text-muted-foreground">From</label>
              <Input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} className="h-9 rounded-lg" />
            </div>
            <div className="space-y-1">
              <label className="text-[11px] font-medium text-muted-foreground">To</label>
              <Input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} className="h-9 rounded-lg" />
            </div>
          </div>
          <div className="flex justify-end">
            <Button variant="ghost" size="sm" className="text-muted-foreground" onClick={clearFilters}>
              <X className="h-4 w-4" /> Clear Filters
            </Button>
          </div>
        </CardContent>
      </Card>

      <Card className="rounded-2xl border-border/60 shadow-soft">
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow className="bg-muted/40">
                  <TableHead className="w-[100px]">Report ID</TableHead>
                  <TableHead>Report Name</TableHead>
                  <TableHead>Assignment</TableHead>
                  <TableHead>Type</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead>Date</TableHead>
                  <TableHead>Format</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {paged.length === 0 && (
                  <TableRow>
                    <TableCell colSpan={8} className="py-16 text-center text-sm text-muted-foreground">
                      <FileBarChart className="mx-auto mb-2 h-8 w-8 opacity-40" />
                      No reports match your filters.
                    </TableCell>
                  </TableRow>
                )}
                {paged.map((r) => (
                  <TableRow key={r.id} className="hover:bg-muted/30">
                    <TableCell className="font-mono text-xs text-muted-foreground">{r.id}</TableCell>
                    <TableCell className="font-medium">{r.name}</TableCell>
                    <TableCell>{r.assignmentName}</TableCell>
                    <TableCell>
                      <Badge variant="outline" className="rounded-full border-primary/20 bg-primary/5 text-primary">
                        {r.assignmentType}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-sm">{r.generatedBy}</TableCell>
                    <TableCell className="text-sm text-muted-foreground">{formatDate(r.generatedDate)}</TableCell>
                    <TableCell>
                      <span
                        className={`inline-flex items-center gap-1 rounded-full px-2.5 py-0.5 text-xs font-medium ring-1 ${
                          r.format === "PDF"
                            ? "bg-rose-50 text-rose-700 ring-rose-200"
                            : "bg-emerald-50 text-emerald-700 ring-emerald-200"
                        }`}
                      >
                        {r.format === "PDF" ? <FileText className="h-3 w-3" /> : <FileSpreadsheet className="h-3 w-3" />}
                        {r.format}
                      </span>
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-1">
                        <Button size="icon" variant="ghost" className="h-8 w-8 rounded-lg" title="View" onClick={() => toast.info(`Opening ${r.id}`)}>
                          <Eye className="h-4 w-4" />
                        </Button>
                        <Button size="icon" variant="ghost" className="h-8 w-8 rounded-lg" title="Download PDF" onClick={() => toast.success(`Downloaded ${r.id}.pdf`)}>
                          <FileText className="h-4 w-4" />
                        </Button>
                        <Button size="icon" variant="ghost" className="h-8 w-8 rounded-lg" title="Download Excel" onClick={() => toast.success(`Downloaded ${r.id}.xlsx`)}>
                          <FileSpreadsheet className="h-4 w-4" />
                        </Button>
                        <Button
                          size="icon"
                          variant="ghost"
                          className="h-8 w-8 rounded-lg text-destructive hover:text-destructive"
                          title="Delete"
                          onClick={() => setToDelete(r)}
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>

          <div className="flex flex-col items-center justify-between gap-3 border-t p-4 md:flex-row">
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <span>Rows per page</span>
              <Select value={String(pageSize)} onValueChange={(v) => { setPageSize(Number(v)); setPage(1); }}>
                <SelectTrigger className="h-8 w-[80px] rounded-lg"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {[10, 25, 50, 100].map((n) => <SelectItem key={n} value={String(n)}>{n}</SelectItem>)}
                </SelectContent>
              </Select>
              <span>
                {(currentPage - 1) * pageSize + 1}-{Math.min(currentPage * pageSize, filtered.length)} of {filtered.length}
              </span>
            </div>
            <div className="flex items-center gap-1">
              <Button variant="outline" size="sm" className="rounded-lg" disabled={currentPage === 1} onClick={() => setPage(currentPage - 1)}>
                <ChevronLeft className="h-4 w-4" /> Prev
              </Button>
              <span className="px-3 text-sm tabular-nums">{currentPage} / {totalPages}</span>
              <Button variant="outline" size="sm" className="rounded-lg" disabled={currentPage === totalPages} onClick={() => setPage(currentPage + 1)}>
                Next <ChevronRight className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      <AlertDialog open={!!toDelete} onOpenChange={(o) => !o && setToDelete(null)}>
        <AlertDialogContent className="rounded-2xl">
          <AlertDialogHeader>
            <AlertDialogTitle>Delete report?</AlertDialogTitle>
            <AlertDialogDescription>
              This permanently removes <span className="font-semibold">{toDelete?.name}</span>. This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel className="rounded-lg">Cancel</AlertDialogCancel>
            <AlertDialogAction
              className="rounded-lg bg-destructive text-destructive-foreground hover:bg-destructive/90"
              onClick={() => {
                if (toDelete) {
                  setRows(rows.filter((r) => r.id !== toDelete.id));
                  toast.success(`Deleted ${toDelete.id}`);
                  setToDelete(null);
                }
              }}
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </DashboardShell>
  );
}
