/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsHistoryRouteImport } from './routes/reports.history'
import { Route as AssignmentsNewRouteImport } from './routes/assignments.new'
import { Route as AssignmentsHistoryRouteImport } from './routes/assignments.history'
import { Route as AssignmentsIdRouteImport } from './routes/assignments.$id'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsHistoryRoute = ReportsHistoryRouteImport.update({
  id: '/reports/history',
  path: '/reports/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsNewRoute = AssignmentsNewRouteImport.update({
  id: '/assignments/new',
  path: '/assignments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsHistoryRoute = AssignmentsHistoryRouteImport.update({
  id: '/assignments/history',
  path: '/assignments/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsIdRoute = AssignmentsIdRouteImport.update({
  id: '/assignments/$id',
  path: '/assignments/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/templates': typeof TemplatesRoute
  '/assignments/$id': typeof AssignmentsIdRoute
  '/assignments/history': typeof AssignmentsHistoryRoute
  '/assignments/new': typeof AssignmentsNewRoute
  '/reports/history': typeof ReportsHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/templates': typeof TemplatesRoute
  '/assignments/$id': typeof AssignmentsIdRoute
  '/assignments/history': typeof AssignmentsHistoryRoute
  '/assignments/new': typeof AssignmentsNewRoute
  '/reports/history': typeof ReportsHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/templates': typeof TemplatesRoute
  '/assignments/$id': typeof AssignmentsIdRoute
  '/assignments/history': typeof AssignmentsHistoryRoute
  '/assignments/new': typeof AssignmentsNewRoute
  '/reports/history': typeof ReportsHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/templates'
    | '/assignments/$id'
    | '/assignments/history'
    | '/assignments/new'
    | '/reports/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/templates'
    | '/assignments/$id'
    | '/assignments/history'
    | '/assignments/new'
    | '/reports/history'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/templates'
    | '/assignments/$id'
    | '/assignments/history'
    | '/assignments/new'
    | '/reports/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TemplatesRoute: typeof TemplatesRoute
  AssignmentsIdRoute: typeof AssignmentsIdRoute
  AssignmentsHistoryRoute: typeof AssignmentsHistoryRoute
  AssignmentsNewRoute: typeof AssignmentsNewRoute
  ReportsHistoryRoute: typeof ReportsHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/history': {
      id: '/reports/history'
      path: '/reports/history'
      fullPath: '/reports/history'
      preLoaderRoute: typeof ReportsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/new': {
      id: '/assignments/new'
      path: '/assignments/new'
      fullPath: '/assignments/new'
      preLoaderRoute: typeof AssignmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/history': {
      id: '/assignments/history'
      path: '/assignments/history'
      fullPath: '/assignments/history'
      preLoaderRoute: typeof AssignmentsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/$id': {
      id: '/assignments/$id'
      path: '/assignments/$id'
      fullPath: '/assignments/$id'
      preLoaderRoute: typeof AssignmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TemplatesRoute: TemplatesRoute,
  AssignmentsIdRoute: AssignmentsIdRoute,
  AssignmentsHistoryRoute: AssignmentsHistoryRoute,
  AssignmentsNewRoute: AssignmentsNewRoute,
  ReportsHistoryRoute: ReportsHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
